package com.aadityatiwari.learn.webservices.temperature;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 *
 * <B>DO NOT EDIT!</B><BR>
 * This class was generated by <I>wsdlc</I> on <I>Mon Apr 07 23:41:04 PDT 2014</I>.
 *
 */

@WebService(
  name="TemperaturePortType",
  targetNamespace="http://www.xmethods.net/sd/TemperatureService.wsdl")
@SOAPBinding(style=SOAPBinding.Style.DOCUMENT, use=SOAPBinding.Use.LITERAL,parameterStyle=SOAPBinding.ParameterStyle.BARE)
public interface TemperaturePortType {
 
  /**
   * <B>getTemp</B> is exposed as a Web Service Operation
   * 
   */
  @WebMethod(    action="",
    operationName="getTemp")
  @WebResult(name="return")  
  public float getTemp(@WebParam(name="zip") java.lang.String zip)
    ;
 }